### ISSUE TITLE
WARNING: Illegal reflective access using Lookup on org.modelmapper.internal.ProxyFactory to interface java.util.Set

### ISSUE THREAD

**Issue by jrry** [modelmapper/modelmapper#414]
Hi, i have a warning in console when i convert Set to String separated by comma. How to fix it?
ModelMapper version 2.3.1
Compiled with jdk 11 and jdk 10

> WARNING: Illegal reflective access using Lookup on org.modelmapper.internal.ProxyFactory (file:/C:/Users/dev/.m2/repository/org/modelmapper/modelmapper/2.3.0/modelmapper-2.3.0.jar) to interface java.util.Set

```
class ClassWithSet {
	private Set<Human> people;
	// getter, setter
}

class ClassWithString {
	private String names;
	// getter, setter
}

class Human {
	private String name;
	private String surname;
	// getter, setter
}

Converter<Set<Human>, String> setToStringComma =
                source -> source.getSource().stream().map(Human::getName).collect(Collectors.joining(","));

modelMapper.typeMap(ClassWithSet.class, ClassWithString.class)
                .addMappings(mapper -> mapper.using(setToStringComma).map(ClassWithSet::getPeople, ClassWithString::setNames));
```

**Comment by chhsiao90** [comment]
Hi @jrry ,

We are still not working with new Java module system. So it's expected behavior the compiler complains about this kind of problems.

**Comment by Martin-BG** [comment]
Hi @chhsiao90,

I'm having a similar issue caused by Java module system, but on a slightly different scenario.

I have 2 classes with no getters/setters that I want to use mapping on and in order to do that I have field access set as follows:

```java
    @Bean
    ModelMapper createModelMapper() {
        ModelMapper modelMapper = new ModelMapper();

        modelMapper.getConfiguration()
                .setFieldAccessLevel(org.modelmapper.config.Configuration.AccessLevel.PRIVATE)
                .setFieldMatchingEnabled(true);

        return modelMapper;
    }
```
Everything works as expected, except that I'm getting the famous **An illegal reflective access operation has occurred** warning:

> WARNING: Illegal reflective access by org.modelmapper.internal.PropertyInfoImpl$FieldPropertyInfo (file:/home/martin/.m2/repository/org/modelmapper/modelmapper/2.3.2/modelmapper-2.3.2.jar) to field java.math.BigDecimal.intVal

Please let me know if I should open a new ticket for this or if you need more information on the setup.

**Comment by andrewfinnell** [comment]
I'm curious as to why reflection on Lookup is being used to begin with as all the methods being used in `ProxyFactory` are public. As the JDK is already at version 12 now, it becomes more difficult to use this library with these warnings.

**Comment by CrNix** [comment]
Hi, any updates on these kind of issues?

We have these kind of warnings in our Spring Boot application. Can we fix them?

**Comment by peterstritzinger** [comment]
Hi,
the problem is still presend in my Spring Boot application. 

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.modelmapper.internal.ProxyFactory (file:/C:/xxx/peters/.m2/repository/org/modelmapper/modelmapper/2.3.0/modelmapper-2.3.0.jar) to class java.util.Date
WARNING: Please consider reporting this to the maintainers of org.modelmapper.internal.ProxyFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by SVaeth** [comment]
This is issue is still occurring in jdk 11.0.4. If it is not resolved we will have to refactor to not use ModelMapper altogether

**Comment by Clemens-E** [comment]
Having the same issue:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.modelmapper.internal.PropertyInfoImpl$AbstractMethodInfo (file:/app/lib/modelmapper-2.3.0.jar) to method java.util.Date.getCalendarDate()
WARNING: Please consider reporting this to the maintainers of org.modelmapper.internal.PropertyInfoImpl$AbstractMethodInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
This is Issue exists since over one year, is there no intention to fix it?

**Comment by achintSatsangi** [comment]
Seeing the same warnings with latest springboot , jdk 11 while mapping between two classes... Any plans of fixing this?????

**Comment by jemag** [comment]
Similar problem with jdk 11.0.6 and modelmapper 2.3.7:
![image](https://user-images.githubusercontent.com/7985687/78300089-f2ad8b00-7504-11ea-8b01-f4c7159e6834.png)

There hasn't been any feedback from members of the project on this issue since 2018, could we just get a brief status of the situation on this issue ? @chhsiao90 @jhalterman

**Comment by rboarman-sc** [comment]
Bump

**Comment by DenisO-AVISPL** [comment]
JVM Version:           14.0.1+7
modelmapper          2.3.8

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.modelmapper.internal.ProxyFactory (file:/Users/*****/IdeaProjects/*****/WEB-INF/lib/modelmapper-2.3.8.jar) to interface java.util.Map
WARNING: Please consider reporting this to the maintainers of org.modelmapper.internal.ProxyFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by stochmalm** [comment]
I found out that this type mapping config will cause this issue:

```
ModelMapper modelMapper = new ModelMapper();
modelMapper.addMappings(new PropertyMap<Source, Dest>() {
          @Override
          protected void configure() {
              skip(source.getSomething());
          }
      });
```

but this doesn't:

```   
ModelMapper modelMapper = new ModelMapper();
modelMapper.typeMap(Source.class, Dest.class).addMappings(
            mapper -> mapper.skip(Dest::setSomething));
```

**Comment by iNomaD** [comment]
The same issue
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
modelmapper 2.3.8
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.modelmapper.internal.PropertyInfoImpl$FieldPropertyInfo (file:/Users/***/.gradle/caches/modules-2/files-2.1/org.modelmapper/modelmapper/2.3.8/9cfa7d9ea8d0ccdd6a91f3331f54c1938ff15ae0/modelmapper-2.3.8.jar) to field java.time.LocalDate.year
WARNING: Please consider reporting this to the maintainers of org.modelmapper.internal.PropertyInfoImpl$FieldPropertyInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by AlexRogalskiy** [comment]
Still have the same problem while working with ModelMapper:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.modelmapper.internal.PropertyInfoImpl$FieldPropertyInfo (file:/C:/Users/ARogalsky/.m2/repository/org/modelmapper/modelmapper/2.3.8/modelmapper-2.3.8.jar) to field java.util.UUID.mostSigBits
WARNING: Please consider reporting this to the maintainers of org.modelmapper.internal.PropertyInfoImpl$FieldPropertyInfo
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by RoseRiyadh** [comment]
jdk 14 still have the same problem 
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.modelmapper.internal.ProxyFactory (file:/home/rose/.m2/repository/org/modelmapper/modelmapper/2.3.8/modelmapper-2.3.8.jar) to class java.util.Date
WARNING: Please consider reporting this to the maintainers of org.modelmapper.internal.ProxyFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by Y00sh00** [comment]
For anyone reading this that is in a similar situation as me. On JDK 11 and modelMapper version 2.3.8. I had the following config.

`
ModelMapper modelMapper = new ModelMapper();
        modelMapper.getConfiguration()
                .setFieldMatchingEnabled(true)
                .setFieldAccessLevel(org.modelmapper.config.Configuration.AccessLevel.PRIVATE)
                .setMatchingStrategy(MatchingStrategies.STRICT);


        return modelMapper;
`

Since I didn't strictly need setFieldAccessLevel for my usecase, removing `.setFieldAccessLevel(org.modelmapper.config.Configuration.AccessLevel.PRIVATE)` removed the warning for me.

**Comment by myst3k** [comment]
> For anyone reading this that is in a similar situation as me. On JDK 11 and modelMapper version 2.3.8. I had the following config.
> 
> `ModelMapper modelMapper = new ModelMapper(); modelMapper.getConfiguration() .setFieldMatchingEnabled(true) .setFieldAccessLevel(org.modelmapper.config.Configuration.AccessLevel.PRIVATE) .setMatchingStrategy(MatchingStrategies.STRICT); return modelMapper;`
> 
> Since I didn't strictly need setFieldAccessLevel for my usecase, removing `.setFieldAccessLevel(org.modelmapper.config.Configuration.AccessLevel.PRIVATE)` removed the warning for me.

Same here, Kotlin 1.4.10, ModelMapper 2.3.8, removed Private level access and issue went away. Ran into the issue on a public var with type java.time.LocalDateTime

Also tested changing to Package_Private and the issue was resolved.

**Comment by dan-earle** [comment]
It went away for me when I upgraded to 2.3.9

**Comment by chhsiao90** [comment]
ModelMapper 2.4.0 released.

**Comment by KayTwoKay** [comment]
Don't think it's fixed yet https://github.com/modelmapper/modelmapper/issues/629

**Comment by spopida** [comment]
Seems to have been fixed - I'm using v3.0.0 and warnings relating to BigDecimal have disappeared :-)

**Comment by DagleAnderson** [comment]
Não sei se fico com raiva ou feliz .rsrs... estou com meu projeto há um 1 ano levando certa de 15 min pra compilar . Tinha implementado o model mapper 2.3.0 . E aparecia essa mensagem e ainda demorava no build. ha tinha pesquisado já sobre mas não fui a fundo pq "estava funcionando". Mas hoje foi o cumulo , estava levando 20 min .. ai não da. Agora por fim joguei a versão v 3.0.0 , a mensagem sumiu , o projeto builda em menos de 1 min e ta tudo rodando.

**Comment by DagleAnderson** [comment]
551 / 5.000
Resultados de tradução
Resultado da tradução
I don't know if I'm happy or very angry. ha.... Because, it's been a while since my project has been taking about 15 minutes to build my app. I noticed that after implementing model mapper 2.3.0 in my project it got slower. But... it was working, so I decided to just not fix it. But today, definitely, this situation has become very stressful. Thank goodness the friend commented that there is a version that works. I just updated my version to 3.0.0 and now my project is working perfectly.

**Comment by DagleAnderson** [comment]
I don't know if I'm happy or very angry. ha.... Because, it's been a while since my project has been taking about 15 minutes to build my app. I noticed that after implementing model mapper 2.3.0 in my project it got slower. But... it was working, so I decided to just not fix it. But today, definitely, this situation has become very stressful. Thank goodness the friend commented that there is a version that works. I just updated my version to 3.0.0 and now my project is working perfectly.

**Comment by MiguelSanchezNavis** [comment]
I´m not able to fix this... 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.modelmapper.internal.ProxyFactory (file: ... modelmapper-2.3.8.jar) to class java.util.Date
WARNING: Please consider reporting this to the maintainers of org.modelmapper.internal.ProxyFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Tried to upgrade up to model mapper 3.0.0 but is still failing for me. Everything happened when upgrading from Java8 to Java11 and springboot version from 2.3.x to 2.7.x

In my case is java.util.Date, I´ve tried everything proposed here in this thread... I don´t think is fixed yet

**Comment by ernestorumo** [comment]
> I´m not able to fix this...
> 
> WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access using Lookup on org.modelmapper.internal.ProxyFactory (file: ... modelmapper-2.3.8.jar) to class java.util.Date WARNING: Please consider reporting this to the maintainers of org.modelmapper.internal.ProxyFactory WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release
> 
> Tried to upgrade up to model mapper 3.0.0 but is still failing for me. Everything happened when upgrading from Java8 to Java11 and springboot version from 2.3.x to 2.7.x
> 
> In my case is java.util.Date, I´ve tried everything proposed here in this thread... I don´t think is fixed yet

I have the same error with modelmapper 3.1.0 and springboot 2.7.13
